# ДЛЯ ТОГО, ЧТОБЫ ХУКИ НАЧАЛИ ДЕЙСТВОВАТЬ ВЫПОЛНИТЬ КОМАНДУ pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.5
    hooks:
      # Run the linter.
      - id: ruff

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        language: system
        entry: pytest
        args:
          [--cov=app/ --cov-report=xml --cov-report=html --cov-branch ./tests/]
        pass_filenames: false


  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy --config-file=pyproject.toml
        language: python
        'types_or': [ python, pyi ]
        require_serial: true

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
